// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project ca611bf9ae534859 "SignatureAPI", do not edit manually */
// virtual:__routes
var routes = {
  "DhvwGaaou": {
    "path": "/home-backup"
  },
  "DiKMHAohF": {
    "path": "/blog/:slug"
  },
  "I4RMCmkQd": {
    "path": "/e-signature-news"
  },
  "KSjCJwy_s": {
    "path": "/blog"
  },
  "NukTy_VHU": {
    "path": "/home-2"
  },
  "OL4NtcSBu": {
    "path": "/pricing"
  },
  "QqS4d__RJ": {
    "path": "/changelog"
  },
  "augiA20Il": {
    "path": "/"
  },
  "elJhlphhA": {
    "path": "/pricing-3"
  },
  "kw24qmVnO": {
    "path": "/pricing-2"
  },
  "pCsjntyo1": {
    "path": "/e-signature-news-2"
  },
  "wKxO4rmxX": {
    "path": "/home-for-export"
  }
};

export {
  routes
};
